# Configuration file | MyBan v. 1.0 by karlov_m

offline-players: true
oof: "&f[&6MyBan&f] &cYou can't mute or ban offline player"

no-perm: "&f[&6MyBan&f] &cYou do not have permission"
whatban: "&f[&6MyBan&f] &cPlease use /rban <player> <time in minutes> <reason>"
whatmute: "&f[&6MyBan&f] &cPlease use /rmute <player> <minutes> <reason>"

cunban: "&f[&6MyBan&f] &cCan't unban (the player is not banned)"
cunmute: "&f[&6MyBan&f] &cCan't unmute (the player is not muted)"

unmute: "&f[&6MyBan&f] &aPlayer &6%s unmuted"
unban: "&f[&6MyBan&f] &aPlayer &6%s unbanned"

ban: "&f[&6MyBan&f] &cYou have been banned for %s minutes: &6%z"
banh: "&f[&6MyBan&f] &6You banned %s for %k minutes:&f %z"

mute: "&f[&6MyBan&f] &cYou have been muted for %s minutes: &6%z"
muteh: "&f[&6MyBan&f] &6You muted %s for %k minutes:&f %z"

time: "&f[&6MyBan&f] &cYou have only %t minutes maximum"

nan: "&f[&6MyBan&f] &cWrong number"
args: "&f[&6MyBan&f] &cWrong arguments"
