# Configuration file | MyBan v. 1.0 by karlov_m

offline-players: true
oof: "&cВзаимодейтвовать с оффлайн-игроками запрещено"

no-perm: "&cУ вас нет разрешения"
whatban: "&cИпользуйте /rban <игрок> <минуты> <причина>"
whatmute: "&cИпользуйте /rmute <игрок> <минуты> <причина>"

cunban: "&cНевозможно разбанить(не забанен)"
cunmute: "&cНевозможно размутить(не заглушен)"

unmute: "&aИгрок &6%s размучен"
unban: "&aИгрок &6%s разбанен"

ban: "&cВы забанены на %s минут по причине: &6%z"
banh: "&6Вы забанили игрока %s на %k минут по причине:&f %z"

mute: "&cВы заглушены на %s минут по причине: &6%z"
muteh: "&6Вы заглушили игрока %s на %k минут по причине:&f %z"

time: "&cВам доступно максимум %t минут"

nan: "&cНеверное число"
args: "&cНеверные аргументы"
